alter table profiles enable row level security;
alter table love_cvs enable row level security;
alter table photos enable row level security;
alter table profile_views enable row level security;
alter table reports enable row level security;
alter table story_exports enable row level security;
create policy "public read profiles" on profiles for select using (is_public=true);
create policy "owner all profiles" on profiles for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "public read cv" on love_cvs for select using (exists (select 1 from profiles p where p.id=love_cvs.profile_id and p.is_public=true));
create policy "owner all cv" on love_cvs for all to authenticated using (exists (select 1 from profiles p where p.id=love_cvs.profile_id and p.user_id=auth.uid())) with check (exists (select 1 from profiles p where p.id=love_cvs.profile_id and p.user_id=auth.uid()));
create policy "public read photos" on photos for select using (visibility='public');
create policy "owner all photos" on photos for all to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "owner read views" on profile_views for select to authenticated using (exists (select 1 from profiles p where p.id=profile_views.profile_id and p.user_id=auth.uid()));
create policy "auth insert report" on reports for insert to authenticated with check (reporter_user_id=auth.uid());
create policy "owner read story_exports" on story_exports for select to authenticated using (user_id=auth.uid());
create policy "owner insert story_exports" on story_exports for insert to authenticated with check (user_id=auth.uid());
alter table interview_requests enable row level security;
alter table interview_request_events enable row level security;
create policy "owner select interview" on interview_requests for select to authenticated using (sender_id=auth.uid() or receiver_id=auth.uid());
create policy "sender insert interview" on interview_requests for insert to authenticated with check (sender_id=auth.uid() and sender_id<>receiver_id);
create policy "receiver update interview" on interview_requests for update to authenticated using (receiver_id=auth.uid() or sender_id=auth.uid()) with check (receiver_id=auth.uid() or sender_id=auth.uid());
create policy "request parties select events" on interview_request_events for select to authenticated using (exists(select 1 from interview_requests r where r.id=request_id and (r.sender_id=auth.uid() or r.receiver_id=auth.uid())));
create policy "request parties insert events" on interview_request_events for insert to authenticated with check (actor_id=auth.uid());
alter table favorites enable row level security;
alter table discover_preferences enable row level security;
alter table profile_impressions enable row level security;
alter table profile_clicks enable row level security;
create policy "public discover profiles" on profiles for select using (is_public=true and discoverable=true and is_completed=true and moderation_status='active');
create policy "owner favorites all" on favorites for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "owner discover prefs all" on discover_preferences for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "auth insert impressions" on profile_impressions for insert to authenticated with check (viewer_id=auth.uid() or viewer_id is null);
create policy "auth insert clicks" on profile_clicks for insert to authenticated with check (viewer_id=auth.uid() or viewer_id is null);
alter table payments enable row level security;
alter table boosts enable row level security;
alter table premium_entitlements enable row level security;
alter table analytics_events enable row level security;
create policy "owner payments select" on payments for select to authenticated using (user_id=auth.uid());
create policy "owner boosts select" on boosts for select to authenticated using (user_id=auth.uid());
create policy "owner entitlements select" on premium_entitlements for select to authenticated using (user_id=auth.uid());
create policy "owner analytics select" on analytics_events for select to authenticated using (user_id=auth.uid());
create policy "auth analytics insert" on analytics_events for insert to authenticated with check (user_id=auth.uid() or user_id is null);
