import { createServiceClient } from "@/lib/supabase/admin";
import { defaultModelConfigs } from "./defaults";
import type { GenerationRunInput, PromptTemplate, PromptVersion, RoutingRule, SectorRule } from "./types";

type SupabaseLike = ReturnType<typeof createServiceClient>;
function client(supabase?: SupabaseLike) { return supabase ?? createServiceClient(); }

export async function listPromptTemplates(supabase?: SupabaseLike) { const { data, error } = await client(supabase).from("ai_prompt_templates").select("*").order("updated_at", { ascending: false }); if (error) throw error; return data as PromptTemplate[]; }
export async function getPromptTemplate(keyOrId: string, supabase?: SupabaseLike) { const db = client(supabase); const query = db.from("ai_prompt_templates").select("*"); const { data, error } = await (keyOrId.includes(".") ? query.eq("key", keyOrId) : query.eq("id", keyOrId)).maybeSingle(); if (error) throw error; return data as PromptTemplate | null; }
export async function getActivePromptVersion(templateId: string, supabase?: SupabaseLike) { const db = client(supabase); const template = await db.from("ai_prompt_templates").select("active_version_id").eq("id", templateId).maybeSingle<{ active_version_id: string | null }>(); if (template.error) throw template.error; const id = template.data?.active_version_id; const { data, error } = id ? await db.from("ai_prompt_versions").select("*").eq("id", id).maybeSingle() : await db.from("ai_prompt_versions").select("*").eq("template_id", templateId).eq("status", "active").order("version_number", { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data as PromptVersion | null; }
export async function createPromptTemplate(input: Partial<PromptTemplate> & { key: string; name: string; type: string }, supabase?: SupabaseLike) { const { data, error } = await client(supabase).from("ai_prompt_templates").insert(input).select("*").single(); if (error) throw error; return data as PromptTemplate; }
export async function createPromptVersion(input: Partial<PromptVersion> & { template_id: string; system_prompt: string; user_prompt_template: string }, supabase?: SupabaseLike) { const db = client(supabase); const existing = await db.from("ai_prompt_versions").select("version_number").eq("template_id", input.template_id).order("version_number", { ascending: false }).limit(1).maybeSingle<{ version_number: number }>(); const version_number = input.version_number ?? ((existing.data?.version_number ?? 0) + 1); const { data, error } = await db.from("ai_prompt_versions").insert({ ...input, version_number }).select("*").single(); if (error) throw error; return data as PromptVersion; }
export async function activatePromptVersion(templateId: string, versionId: string, userId?: string | null, supabase?: SupabaseLike) { const db = client(supabase); await db.from("ai_prompt_versions").update({ status: "archived" }).eq("template_id", templateId).eq("status", "active"); const version = await db.from("ai_prompt_versions").update({ status: "active", activated_by: userId ?? null, activated_at: new Date().toISOString() }).eq("id", versionId).select("*").single(); if (version.error) throw version.error; const template = await db.from("ai_prompt_templates").update({ active_version_id: versionId, status: "active", updated_at: new Date().toISOString() }).eq("id", templateId).select("*").single(); if (template.error) throw template.error; return { template: template.data as PromptTemplate, version: version.data as PromptVersion }; }
export async function rollbackPromptVersion(templateId: string, userId?: string | null, supabase?: SupabaseLike) { const { data, error } = await client(supabase).from("ai_prompt_versions").select("id").eq("template_id", templateId).neq("status", "archived").order("version_number", { ascending: false }).limit(2); if (error) throw error; const previous = data?.[1]?.id ?? data?.[0]?.id; if (!previous) throw new Error("No prompt version available for rollback"); return activatePromptVersion(templateId, previous, userId, supabase); }
export async function listSectorRules(supabase?: SupabaseLike) { const { data, error } = await client(supabase).from("ai_sector_rules").select("*").order("key"); if (error) throw error; return data as SectorRule[]; }
export async function listModelConfigs(supabase?: SupabaseLike) { if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return defaultModelConfigs; const { data, error } = await client(supabase).from("ai_model_configs").select("*").order("provider"); if (error) throw error; return data?.length ? data : defaultModelConfigs; }
export async function getRoutingRule(taskType: string, sector?: string | null, supabase?: SupabaseLike) { const { data, error } = await client(supabase).from("ai_routing_rules").select("*").eq("task_type", taskType).or(`sector.is.null,sector.eq.${sector ?? ""}`).eq("status", "active").limit(1).maybeSingle(); if (error) throw error; return data as RoutingRule | null; }
export async function createGenerationRun(input: GenerationRunInput, supabase?: SupabaseLike) { if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return { id: null, skipped: true }; const payload = { user_id: input.userId ?? null, job_id: input.jobId ?? null, job_row_id: input.jobRowId ?? null, proposal_id: input.proposalId ?? null, proposal_version_id: input.proposalVersionId ?? null, template_id: input.templateId ?? null, prompt_version_id: input.promptVersionId ?? null, sector_rule_id: input.sectorRuleId ?? null, task_type: input.taskType, provider: input.provider, model: input.model, prompt_version_label: input.promptVersionLabel ?? null, input_tokens: input.inputTokens ?? null, output_tokens: input.outputTokens ?? null, total_tokens: (input.inputTokens ?? 0) + (input.outputTokens ?? 0) || null, estimated_cost: input.estimatedCost ?? null, latency_ms: input.latencyMs ?? null, status: input.status ?? (input.fallbackUsed ? "fallback" : "completed"), fallback_used: Boolean(input.fallbackUsed), fallback_reason: input.fallbackReason ?? null, quality_score: input.qualityScore ?? null, warnings: input.warnings ?? [], quality_audit: input.qualityAudit ?? {}, prompt_input_hash: input.promptInputHash ?? null, output_hash: input.outputHash ?? null }; const { data, error } = await client(supabase).from("ai_generation_runs").insert(payload).select("id").single<{ id: string }>(); return { id: data?.id ?? null, skipped: false, error: error?.message } as const; }
