export type PromptTemplateType = "product" | "category" | "metadata" | "alt_text" | "schema" | "faq" | "article" | "repair_json" | "product_regeneration" | "field_regeneration" | "free_audit_summary" | "gsc_opportunity" | "import_mapping_assistant";
export type AiStatus = "draft" | "active" | "paused" | "archived";
export type AiProviderName = "openai" | "openai_compatible" | "qwen" | "deepseek" | "anthropic" | "gemini" | "mock" | "template_fallback";

export type PromptTemplate = { id: string; key: string; name: string; description?: string | null; type: PromptTemplateType; status: AiStatus; default_locale: string; default_tone?: string | null; default_sector?: string | null; active_version_id?: string | null; created_at?: string; updated_at?: string };
export type PromptVersion = { id: string; template_id: string; version_number: number; status: AiStatus; system_prompt: string; user_prompt_template: string; output_schema?: Record<string, unknown>; variables_schema?: Record<string, unknown>; model_policy?: Record<string, unknown>; quality_policy?: Record<string, unknown>; safety_policy?: Record<string, unknown>; changelog?: string | null; activated_at?: string | null };
export type SectorRule = { id?: string; key: string; name: string; sector: string; tone?: string | null; locale?: string; allowed_claims?: string[]; forbidden_claims?: string[]; required_fields?: string[]; recommended_keywords?: string[]; forbidden_keywords?: string[]; writing_guidelines?: Record<string, unknown>; seo_guidelines?: Record<string, unknown>; compliance_notes?: Record<string, unknown>; status?: "active" | "paused" | "archived" };
export type ModelConfig = { provider: AiProviderName; model: string; display_name: string; status: "active" | "paused" | "archived"; supports_json: boolean; input_cost_per_1m?: number | null; output_cost_per_1m?: number | null; quality_tier: "cheap" | "standard" | "premium" | "experimental"; latency_tier?: string };
export type RoutingRule = { task_type: string; sector?: string | null; plan_key?: string | null; primary_provider: AiProviderName; primary_model: string; fallback_provider?: AiProviderName | null; fallback_model?: string | null; max_cost_per_item?: number | null; max_latency_ms?: number | null; status?: "active" | "paused" | "archived" };
export type GenerationRunInput = { userId?: string | null; jobId?: string | null; jobRowId?: string | null; proposalId?: string | null; proposalVersionId?: string | null; templateId?: string | null; promptVersionId?: string | null; sectorRuleId?: string | null; taskType: string; provider: string; model: string; promptVersionLabel?: string | null; inputTokens?: number | null; outputTokens?: number | null; estimatedCost?: number | null; latencyMs?: number | null; status?: "completed" | "failed" | "fallback" | "cancelled"; fallbackUsed?: boolean; fallbackReason?: string | null; qualityScore?: number | null; warnings?: unknown[]; qualityAudit?: Record<string, unknown>; promptInputHash?: string | null; outputHash?: string | null };
export type RenderedPrompt = { systemPrompt: string; userPrompt: string; promptVersionId: string; templateId: string; promptVersionLabel: string; missingVariables: string[] };
