listening-port=3478
fingerprint
lt-cred-mech
realm=tuweb.com
user=rtc:REPLACE_WITH_TURN_PASS
no-stdout-log
no-multicast-peers
stale-nonce=600
cipher-list="HIGH"
# tls-listening-port=5349
# cert=/etc/letsencrypt/live/turn.tuweb.com/fullchain.pem
# pkey=/etc/letsencrypt/live/turn.tuweb.com/privkey.pem
