import crypto from "node:crypto";
import { assertGscEnabled } from "./config";
export function generateOAuthStateValue() { return crypto.randomBytes(32).toString("base64url"); }
export function createCodeVerifier() { return crypto.randomBytes(48).toString("base64url"); }
export function createCodeChallenge(verifier: string) { return crypto.createHash("sha256").update(verifier).digest("base64url"); }
export function buildGoogleAuthUrl({ state, codeChallenge }: { state: string; codeChallenge?: string }) { const c = assertGscEnabled(); const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.searchParams.set("client_id", c.clientId!); url.searchParams.set("redirect_uri", c.redirectUri!); url.searchParams.set("response_type", "code"); url.searchParams.set("scope", c.scopes); url.searchParams.set("access_type", "offline"); url.searchParams.set("prompt", "consent"); url.searchParams.set("state", state); if (codeChallenge) { url.searchParams.set("code_challenge", codeChallenge); url.searchParams.set("code_challenge_method", "S256"); } return url.toString(); }
export async function exchangeCodeForTokens(code: string, codeVerifier?: string) { const c = assertGscEnabled(); const body = new URLSearchParams({ code, client_id: c.clientId!, client_secret: c.clientSecret!, redirect_uri: c.redirectUri!, grant_type: "authorization_code" }); if (codeVerifier) body.set("code_verifier", codeVerifier); const res = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body, cache: "no-store" }); if (!res.ok) throw new Error("google_token_exchange_failed"); return await res.json() as { access_token: string; refresh_token?: string; expires_in?: number; token_type?: string; scope?: string; id_token?: string }; }
export async function refreshAccessToken(refreshToken: string) { const c = assertGscEnabled(); const body = new URLSearchParams({ refresh_token: refreshToken, client_id: c.clientId!, client_secret: c.clientSecret!, grant_type: "refresh_token" }); const res = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body, cache: "no-store" }); if (!res.ok) throw new Error("google_token_refresh_failed"); return await res.json() as { access_token: string; expires_in?: number; token_type?: string; scope?: string }; }
export async function revokeGoogleToken(token: string) { await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(token)}`, { method: "POST" }).catch(() => null); }
