import type { SupabaseClient } from "@supabase/supabase-js";
import { decryptToken, encryptToken } from "./token-crypto";
import { refreshAccessToken } from "./oauth";
type GscConnectionRecord = { id: string; access_token_encrypted: string | null; refresh_token_encrypted: string | null; expiry_date: string | null; token_type?: string | null; scope?: string | null; status?: string | null };
type GscTotals = { clicks: number; impressions: number; weightedPosition: number };
export async function getActiveGscConnection(client: SupabaseClient, userId: string) { const { data, error } = await client.from("gsc_connections").select("*").eq("user_id", userId).eq("status", "connected").order("created_at", { ascending: false }).limit(1).maybeSingle<GscConnectionRecord>(); if (error) throw error; return data; }
export async function getSelectedGscProperty(client: SupabaseClient, userId: string) { const { data, error } = await client.from("gsc_properties").select("*").eq("user_id", userId).eq("is_selected", true).maybeSingle(); if (error) throw error; return data; }
export async function getUsableAccessToken(client: SupabaseClient, connection: GscConnectionRecord) { if (!connection.access_token_encrypted) throw new Error("gsc_missing_access_token"); const expiry = connection.expiry_date ? +new Date(connection.expiry_date) : 0; if (expiry > Date.now() + 60_000) return decryptToken(connection.access_token_encrypted); if (!connection.refresh_token_encrypted) throw new Error("gsc_missing_refresh_token"); const refreshed = await refreshAccessToken(decryptToken(connection.refresh_token_encrypted)); const expiryDate = new Date(Date.now() + ((refreshed.expires_in ?? 3600) * 1000)).toISOString(); await client.from("gsc_connections").update({ access_token_encrypted: encryptToken(refreshed.access_token), expiry_date: expiryDate, last_refreshed_at: new Date().toISOString(), token_type: refreshed.token_type, scope: refreshed.scope }).eq("id", connection.id); return refreshed.access_token; }
export async function getGscStatus(client: SupabaseClient, userId: string, enabled: boolean) { const connection = await getActiveGscConnection(client, userId).catch(() => null); const property = await getSelectedGscProperty(client, userId).catch(() => null); const sync = property ? (await client.from("gsc_sync_runs").select("id,status,date_range,finished_at,created_at,error_message").eq("user_id", userId).eq("property_id", property.id).order("created_at", { ascending: false }).limit(1).maybeSingle()).data : null; const metrics = property ? (await client.from("gsc_url_metrics").select("clicks,impressions,ctr,position,date_range").eq("user_id", userId).eq("property_id", property.id).eq("date_range", "28d").limit(5000)).data ?? [] : []; const totals = metrics.reduce<GscTotals>((acc, row) => { acc.clicks += Number(row.clicks ?? 0); acc.impressions += Number(row.impressions ?? 0); acc.weightedPosition += Number(row.position ?? 0) * Number(row.impressions ?? 0); return acc; }, { clicks: 0, impressions: 0, weightedPosition: 0 }); return { enabled, connected: Boolean(connection), connectionStatus: connection?.status ?? null, selectedProperty: property ? { id: property.id, siteUrl: property.site_url } : null, lastSync: sync, metrics28d: { clicks: totals.clicks, impressions: totals.impressions, ctr: totals.impressions ? totals.clicks / totals.impressions : 0, position: totals.impressions ? totals.weightedPosition / totals.impressions : 0 } }; }
