import { decodeTextBuffer } from "./encoding";
import { IMPORT_LIMITS } from "./limits";
import { autoMapColumnsWithConfidence } from "./mapping-confidence";
import { detectPlatformFromHeaders } from "./platform-detection";
import { normalizeRows } from "./row-normalizer";
import type { ImportedCatalog, ImportedCatalogRow, ImportWarning } from "./types";
const delimiters = [",", ";", "\t", "|"];
function parseRecords(text: string, delimiter: string) { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < text.length; i++) { const c = text[i], next = text[i + 1]; if (c === '"' && quoted && next === '"') { cell += '"'; i++; } else if (c === '"') quoted = !quoted; else if (c === delimiter && !quoted) { row.push(cell); cell = ""; } else if ((c === "\n" || c === "\r") && !quoted) { if (c === "\r" && next === "\n") i++; row.push(cell); if (row.some((v) => v.trim())) rows.push(row); row = []; cell = ""; } else cell += c; } row.push(cell); if (row.some((v) => v.trim())) rows.push(row); return rows; }
function uniqueHeaders(headers: string[], warnings: ImportWarning[]) { const seen = new Map<string, number>(); return headers.map((h, i) => { const base = h.trim().replace(/^\uFEFF/, "") || `columna_${i + 1}`; const key = base.toLowerCase(); const count = seen.get(key) ?? 0; seen.set(key, count + 1); if (count) { warnings.push({ code: "duplicate_header", message: `Cabecera duplicada “${base}”; renombrada como ${base}_${count + 1}.` }); return `${base}_${count + 1}`; } return base; }); }
export function detectCsvDelimiter(text: string) { const sample = text.split(/\r?\n/).slice(0, 20).join("\n"); let best = { delimiter: ",", score: -1 }; for (const delimiter of delimiters) { const records = parseRecords(sample, delimiter).slice(0, 10); const lengths = records.map((r) => r.length).filter((n) => n > 1); const consistency = lengths.length ? lengths.filter((n) => n === lengths[0]).length / lengths.length : 0; const score = lengths.length * consistency * (lengths[0] ?? 1); if (score > best.score) best = { delimiter, score }; } return best.delimiter; }
export function parseCsvText(text: string, options: { sourceType?: "csv" | "tsv" | "pasted_table"; fileName?: string; delimiter?: string } = {}): ImportedCatalog { const warnings: ImportWarning[] = []; const delimiter = options.delimiter ?? (options.sourceType === "tsv" ? "\t" : detectCsvDelimiter(text)); const records = parseRecords(text.replace(/^\uFEFF/, ""), delimiter); if (!records.length) throw new Error("No se detectaron filas importables."); const headers = uniqueHeaders(records[0], warnings); if (headers.length > IMPORT_LIMITS.maxColumns) throw new Error(`Demasiadas columnas (${headers.length}). Máximo ${IMPORT_LIMITS.maxColumns}.`); let truncatedCells = 0; const rows: ImportedCatalogRow[] = records.slice(1).filter((record) => record.some((v) => v.trim())).map((record, index) => { const raw: Record<string, string> = {}; const rowWarnings: ImportWarning[] = record.length !== headers.length ? [{ code: "irregular_row", message: "La fila tiene un número de columnas distinto a la cabecera.", rowIndex: index }] : []; headers.forEach((header, column) => { let value = record[column] ?? ""; if (value.length > IMPORT_LIMITS.maxCellLength) { value = value.slice(0, IMPORT_LIMITS.maxCellLength); truncatedCells++; rowWarnings.push({ code: "cell_truncated", message: `Celda truncada a ${IMPORT_LIMITS.maxCellLength} caracteres por seguridad.`, rowIndex: index }); } raw[header] = value.trim(); }); return { index, raw, warnings: rowWarnings, errors: [] }; }); const mapped = autoMapColumnsWithConfidence(headers); const normalizedRows = normalizeRows(rows, mapped.mapping); return { sourceType: options.sourceType ?? (delimiter === "\t" ? "tsv" : "csv"), fileName: options.fileName, delimiter, encoding: null, sheetName: null, platformGuess: detectPlatformFromHeaders(headers), headers, rows: normalizedRows, sampleRows: normalizedRows.slice(0, IMPORT_LIMITS.maxRowsFreePreview), mappingSuggestions: mapped.suggestions, stats: { totalRows: rows.length, validRows: rows.filter((r) => !r.errors.length).length, invalidRows: rows.filter((r) => r.errors.length).length, totalColumns: headers.length, truncatedCells, emptyRows: records.length - rows.length - 1 }, warnings: [...warnings, ...rows.flatMap((r) => r.warnings)], errors: rows.flatMap((r) => r.errors) }; }
export function parseCsvBuffer(buffer: ArrayBuffer | Uint8Array, options: { fileName?: string; sourceType?: "csv" | "tsv" } = {}) { const decoded = decodeTextBuffer(buffer); const catalog = parseCsvText(decoded.text, { ...options, sourceType: options.sourceType ?? "csv" }); return { ...catalog, encoding: decoded.encoding, warnings: [...decoded.warnings, ...catalog.warnings] } satisfies ImportedCatalog; }
