import { unzipSync, strFromU8 } from "fflate";
import { parseCsvText } from "./csv-importer";
import { IMPORT_LIMITS } from "./limits";
import type { ImportedCatalog } from "./types";
function xmlEscapeDecode(value: string) { return value.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&apos;/g, "'"); }
function colIndex(cellRef: string) { const letters = cellRef.replace(/[^A-Z]/g, ""); return [...letters].reduce((n, c) => n * 26 + c.charCodeAt(0) - 64, 0) - 1; }
function getZip(buffer: Uint8Array) { try { return unzipSync(buffer); } catch { throw new Error("No se pudo abrir el XLSX. El archivo puede estar corrupto o protegido."); } }
function sharedStrings(zip: Record<string, Uint8Array>) { const xml = zip["xl/sharedStrings.xml"] ? strFromU8(zip["xl/sharedStrings.xml"]) : ""; return [...xml.matchAll(/<si[\s\S]*?<\/si>/g)].map((m) => xmlEscapeDecode([...m[0].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map((x) => x[1]).join(""))); }
function sheetFiles(zip: Record<string, Uint8Array>) { return Object.keys(zip).filter((k) => /^xl\/worksheets\/sheet\d+\.xml$/.test(k)).slice(0, IMPORT_LIMITS.maxSheets); }
function workbookSheetNames(zip: Record<string, Uint8Array>) { const xml = zip["xl/workbook.xml"] ? strFromU8(zip["xl/workbook.xml"]) : ""; return [...xml.matchAll(/<sheet\b[^>]*name="([^"]+)"[^>]*>/g)].map((m) => xmlEscapeDecode(m[1])); }
export type WorkbookSheetSummary = { name: string; sheetId: string; rows: number; columns: number };
export function listWorkbookSheets(buffer: ArrayBuffer | Uint8Array): WorkbookSheetSummary[] { const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer); const zip = getZip(bytes); const files = sheetFiles(zip); const names = workbookSheetNames(zip); return files.map((file, index) => { const xml = strFromU8(zip[file]); const rows = (xml.match(/<row\b/g) ?? []).length; const columns = Math.max(...[...xml.matchAll(/<c r="([A-Z]+)\d+"/g)].map((m) => colIndex(m[1]) + 1), 0); return { name: names[index] ?? `Hoja ${index + 1}`, sheetId: file, rows, columns }; }); }
function sheetToTable(zip: Record<string, Uint8Array>, sheetFile: string) { const strings = sharedStrings(zip); const xml = strFromU8(zip[sheetFile]); const rows: string[][] = []; for (const rowMatch of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)) { const values: string[] = []; for (const cell of rowMatch[1].matchAll(/<c([^>]*)>([\s\S]*?)<\/c>/g)) { const attrs = cell[1]; const ref = attrs.match(/r="([A-Z]+)\d+"/)?.[1]; if (!ref) continue; const index = colIndex(ref); const type = attrs.match(/t="([^"]+)"/)?.[1]; const body = cell[2]; const value = body.match(/<v>([\s\S]*?)<\/v>/)?.[1] ?? body.match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1] ?? body.match(/<f>([\s\S]*?)<\/f>/)?.[1] ?? ""; values[index] = type === "s" ? strings[Number(value)] ?? "" : xmlEscapeDecode(value); } if (values.some(Boolean)) rows.push(values); } return rows; }
export function parseSpreadsheet(buffer: ArrayBuffer | Uint8Array, options: { fileName?: string; sheetId?: string } = {}): ImportedCatalog { const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer); const zip = getZip(bytes); const sheets = sheetFiles(zip); if (!sheets.length) throw new Error("El XLSX no contiene hojas legibles."); const sheet = options.sheetId && sheets.includes(options.sheetId) ? options.sheetId : sheets[0]; const rows = sheetToTable(zip, sheet); if (!rows.length) throw new Error("La hoja seleccionada está vacía."); const csv = rows.map((row) => row.map((v) => `"${String(v ?? "").replace(/"/g, '""')}"`).join(",")).join("\n"); const catalog = parseCsvText(csv, { sourceType: "csv", fileName: options.fileName, delimiter: "," }); return { ...catalog, sourceType: "xlsx", sheetName: sheet, warnings: [...catalog.warnings, { code: "xlsx_formula_safe", message: "Las fórmulas de Excel se tratan como valores/texto; Rankelia no ejecuta macros ni fórmulas." }] }; }
export function parseLegacyXls(): never { throw new Error("XLS binario legacy no está habilitado: sube XLSX, CSV o pega la tabla. Rankelia detecta XLS y muestra este error seguro."); }
