import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUserContext } from "@/lib/auth";
import { enforceRateLimit } from "@/lib/rate-limit";
import { createServiceClient } from "@/lib/supabase/admin";
import { assertGscEnabled } from "@/lib/gsc";
export const dynamic = "force-dynamic";
const schema = z.object({ propertyId: z.string().uuid(), dateRanges: z.array(z.enum(["28d", "90d"])).default(["28d", "90d"]), force: z.boolean().optional() });
export async function POST(request: Request) { const context = await getCurrentUserContext(); if (!context.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const user = context.user; const limited = await enforceRateLimit(request, "gsc:sync", user.id, 5, 3600); if (limited) return limited; const parsed = schema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return NextResponse.json({ error: "invalid_payload" }, { status: 400 }); try { assertGscEnabled(); const client = createServiceClient(); const property = (await client.from("gsc_properties").select("id,connection_id,site_url").eq("id", parsed.data.propertyId).eq("user_id", user.id).maybeSingle()).data; if (!property) return NextResponse.json({ error: "gsc_property_not_found" }, { status: 404 }); const inserted = await Promise.all(parsed.data.dateRanges.map((range) => client.from("gsc_sync_runs").insert({ user_id: user.id, connection_id: property.connection_id, property_id: property.id, site_url: property.site_url, status: "queued", date_range: range, dimensions: ["page", "query", "page,query"], mode: "manual" }).select("id,date_range,status").single())); const errors = inserted.map((r) => r.error).filter(Boolean); if (errors.length) return NextResponse.json({ error: errors[0]?.message ?? "gsc_enqueue_failed" }, { status: 500 }); return NextResponse.json({ queued: true, runs: inserted.map((r) => r.data) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "gsc_sync_failed" }, { status: 500 }); } }
