"use client";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Card } from "@/components/ui/Card";
import { Table, Td } from "@/components/ui/Table";
import { useAdminState } from "@/components/admin/AdminStateProvider";
import { getAdminLogs, type AdminJobLogRecord } from "@/lib/db/logs";

function variant(level: string): "success" | "warning" | "danger" | "info" { if (level === "error" || level === "critical") return "danger"; if (level === "warning") return "warning"; return "info"; }
export function RealAdminLogsPage() { const { showToast } = useAdminState(); const [logs, setLogs] = useState<AdminJobLogRecord[]>([]); const [loading, setLoading] = useState(true); useEffect(()=>{ getAdminLogs().then((result)=>{ if (result.error) showToast(result.error.message, "error"); setLogs(result.data ?? []); setLoading(false); }); }, [showToast]); return <div className="space-y-8"><div className="grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-slate-500">Logs reales</p><p className="mt-2 text-3xl font-black">{logs.length}</p></Card><Card><p className="text-sm text-slate-500">Warnings</p><p className="mt-2 text-3xl font-black">{logs.filter(l=>l.level==='warning').length}</p></Card><Card><p className="text-sm text-slate-500">Errores</p><p className="mt-2 text-3xl font-black">{logs.filter(l=>['error','critical'].includes(l.level)).length}</p></Card><Card><p className="text-sm text-slate-500">Worker</p><p className="mt-2 text-3xl font-black">{logs.filter(l=>l.source==='worker').length}</p></Card></div><Card><Badge variant="ai">Worker logs</Badge><h2 className="mt-3 text-xl font-black">Logs e incidencias reales</h2><p className="mb-5 mt-2 text-sm text-slate-500">{loading ? "Cargando…" : "Lectura protegida por rol admin y RLS."}</p><Table headers={["Fecha", "Nivel", "Fuente", "Mensaje", "Usuario", "Job", "Contexto"]}>{logs.map((log)=><tr key={log.id}><Td>{new Date(log.created_at).toLocaleString("es-ES")}</Td><Td><Badge variant={variant(log.level)}>{log.level}</Badge></Td><Td>{log.source}</Td><Td><b>{log.message}</b></Td><Td>{log.profiles?.email ?? log.user_id.slice(0,8)}</Td><Td>{log.jobs?.original_filename ?? log.job_id.slice(0,8)}</Td><Td><code className="text-xs">{log.context ? JSON.stringify(log.context).slice(0,80) : "—"}</code></Td></tr>)}</Table></Card></div>; }
