"use client";
import { useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Table, Td } from "@/components/ui/Table";
import { useAdminState } from "@/components/admin/AdminStateProvider";
import { getAdminJobs, updateJob, type JobRecord } from "@/lib/db/jobs";

type AdminJob = JobRecord & { profiles?: { email?: string; full_name?: string | null } | null };
function variant(status: string): "success" | "warning" | "danger" | "info" | "default" { if (status === "completed") return "success"; if (status.includes("failed") || status === "cancelled") return "danger"; if (["queued", "ready_for_processing", "processing"].includes(status)) return "warning"; if (status === "analyzed") return "info"; return "default"; }
export function RealAdminJobsPage() { const { showToast } = useAdminState(); const [jobs, setJobs] = useState<AdminJob[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<AdminJob | null>(null); async function load() { setLoading(true); const result = await getAdminJobs(); if (result.error) showToast(result.error.message, "error"); setJobs((result.data ?? []) as AdminJob[]); setLoading(false); } useEffect(() => { let active = true; getAdminJobs().then((result) => { if (!active) return; if (result.error) showToast(result.error.message, "error"); setJobs((result.data ?? []) as AdminJob[]); setLoading(false); }); return () => { active = false; }; }, [showToast]); const stats = useMemo(() => ({ total: jobs.length, ready: jobs.filter(j=>j.status === "ready_for_processing").length, failed: jobs.filter(j=>j.status.includes("failed")).length, rows: jobs.reduce((s,j)=>s+j.rows_total,0)}), [jobs]); async function markQueued(job: AdminJob) { const result = await updateJob(job.id, { status: "queued" }); if (result.error) return showToast(result.error.message, "error"); showToast("Job marcado como queued para el worker futuro.", "success"); await load(); }
return <div className="space-y-8"><div className="grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-slate-500">Jobs reales</p><p className="mt-2 text-3xl font-black">{stats.total}</p></Card><Card><p className="text-sm text-slate-500">Ready</p><p className="mt-2 text-3xl font-black">{stats.ready}</p></Card><Card><p className="text-sm text-slate-500">Failed</p><p className="mt-2 text-3xl font-black">{stats.failed}</p></Card><Card><p className="text-sm text-slate-500">Filas</p><p className="mt-2 text-3xl font-black">{stats.rows}</p></Card></div><Card><div className="mb-5"><Badge variant="ai">Datos reales Supabase</Badge><h2 className="mt-3 text-xl font-black">Jobs y cola</h2><p className="text-sm text-slate-500">{loading ? "Cargando…" : "Listado global protegido por rol admin y RLS."}</p></div><Table headers={["ID", "Archivo", "Usuario", "Estado", "Plataforma", "Filas", "Créditos", "Fecha", "Acción"]}>{jobs.map(job => <tr key={job.id}><Td><code>{job.id.slice(0,8)}</code></Td><Td><b>{job.original_filename}</b></Td><Td>{job.profiles?.email ?? job.user_id.slice(0,8)}</Td><Td><Badge variant={variant(job.status)}>{job.status}</Badge></Td><Td>{job.platform}</Td><Td>{job.rows_total}</Td><Td>{job.estimated_credits}</Td><Td>{new Date(job.created_at).toLocaleDateString("es-ES")}</Td><Td><div className="flex gap-2"><Button variant="secondary" onClick={()=>setSelected(job)}>Detalle</Button><Button variant="ghost" onClick={()=>markQueued(job)}>Queued</Button></div></Td></tr>)}</Table></Card>{selected && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/60 px-4 backdrop-blur-sm"><Card className="w-full max-w-3xl" variant="elevated"><div className="flex justify-between"><div><Badge variant={variant(selected.status)}>{selected.status}</Badge><h2 className="mt-3 text-2xl font-black">{selected.original_filename}</h2></div><button className="rounded-2xl border px-3 py-2" onClick={()=>setSelected(null)}>×</button></div><pre className="mt-5 max-h-96 overflow-auto rounded-2xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify({ id: selected.id, user: selected.profiles, analysis: selected.analysis_summary, mapping: selected.column_mapping, storage: selected.input_file_path }, null, 2)}</pre></Card></div>}</div>; }
