"use client";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Card } from "@/components/ui/Card";
import { Table, Td } from "@/components/ui/Table";
import { useAdminState } from "@/components/admin/AdminStateProvider";
import { getAdminUsers } from "@/lib/db/admin";

type AdminUser = { id: string; email: string | null; full_name: string | null; role: string; company_name: string | null; default_platform: string; created_at: string; credit_wallets?: { balance: number; lifetime_used: number } | null; projects?: { id: string }[]; jobs?: { id: string }[] };
export function RealAdminUsersPage() { const { showToast } = useAdminState(); const [users, setUsers] = useState<AdminUser[]>([]); const [loading, setLoading] = useState(true); useEffect(()=>{ let active = true; getAdminUsers().then(result => { if (!active) return; if (result.error) showToast(result.error.message, "error"); setUsers((result.data ?? []) as AdminUser[]); setLoading(false); }); return () => { active = false; }; }, [showToast]); return <div className="space-y-8"><div className="grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-slate-500">Usuarios reales</p><p className="mt-2 text-3xl font-black">{users.length}</p></Card><Card><p className="text-sm text-slate-500">Admins</p><p className="mt-2 text-3xl font-black">{users.filter(u=>u.role==='admin').length}</p></Card><Card><p className="text-sm text-slate-500">Customers</p><p className="mt-2 text-3xl font-black">{users.filter(u=>u.role==='customer').length}</p></Card><Card><p className="text-sm text-slate-500">Créditos globales</p><p className="mt-2 text-3xl font-black">{users.reduce((s,u)=>s+(u.credit_wallets?.balance ?? 0),0).toLocaleString('es-ES')}</p></Card></div><Card><Badge variant="ai">Datos reales Supabase</Badge><h2 className="mt-3 text-xl font-black">Profiles, wallets, projects y jobs</h2><p className="mb-5 mt-2 text-sm text-slate-500">{loading ? 'Cargando…' : 'Lectura global por política admin.'}</p><Table headers={["Usuario", "Email", "Rol", "Créditos", "Proyectos", "Jobs", "Plataforma", "Alta"]}>{users.map(user => <tr key={user.id}><Td><b>{user.full_name ?? 'Sin nombre'}</b></Td><Td>{user.email}</Td><Td><Badge variant={user.role==='admin'?'danger':'success'}>{user.role}</Badge></Td><Td>{(user.credit_wallets?.balance ?? 0).toLocaleString('es-ES')}</Td><Td>{user.projects?.length ?? 0}</Td><Td>{user.jobs?.length ?? 0}</Td><Td>{user.default_platform}</Td><Td>{new Date(user.created_at).toLocaleDateString('es-ES')}</Td></tr>)}</Table></Card></div>; }
