import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUserContext } from "@/lib/auth";
import { enforceRateLimit } from "@/lib/rate-limit";
import { createServiceClient } from "@/lib/supabase/admin";
import { importedRowsToCsv, parsePastedTable, parseImportPreview } from "@/lib/import";
export const dynamic = "force-dynamic";
const pastedSchema = z.object({ pastedText: z.string().max(2_000_000), fileName: z.string().optional() });
export async function POST(request: Request) { const context = await getCurrentUserContext(); if (!context.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const limited = await enforceRateLimit(request, "import:normalize", context.user.id, 30, 300); if (limited) return limited; try { const contentType = request.headers.get("content-type") ?? ""; let catalog; let originalFileName = "pasted-table"; if (contentType.includes("multipart/form-data")) { const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return NextResponse.json({ error: "file_required" }, { status: 400 }); originalFileName = file.name; catalog = await parseImportPreview({ buffer: await file.arrayBuffer(), fileName: file.name, mime: file.type, sheetId: String(form.get("sheetId") ?? "") || undefined }); } else { const parsed = pastedSchema.parse(await request.json()); originalFileName = parsed.fileName ?? "pasted-table"; catalog = parsePastedTable(parsed.pastedText); } const csv = importedRowsToCsv(catalog.headers, catalog.rows); if (process.env.SUPABASE_SERVICE_ROLE_KEY) await createServiceClient().from("import_runs").insert({ user_id: context.user.id, source_type: catalog.sourceType, original_file_name: originalFileName, sheet_name: catalog.sheetName ?? null, encoding: catalog.encoding ?? null, delimiter: catalog.delimiter ?? null, platform_guess: catalog.platformGuess?.platform ?? null, mapping_confidence: catalog.mappingSuggestions?.length ? catalog.mappingSuggestions.reduce((sum, item) => sum + item.confidence, 0) / catalog.mappingSuggestions.length : null, status: "normalized", rows_total: catalog.rows.length, rows_valid: catalog.rows.length, rows_invalid: 0, columns_total: catalog.headers.length, mapping: {}, warnings: catalog.warnings ?? [], errors: [], normalized_storage_path: null }); return NextResponse.json({ csv, fileName: `${catalog.fileName ?? "rankelia-import"}.normalized.csv`, catalog }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "import_normalize_failed" }, { status: 400 }); } }
