import type { Opportunity, GscOpportunityType } from "./types";
import { clampOpportunityScore, priorityFromScore } from "./scoring";
const n = (v: unknown) => Number.isFinite(Number(v)) ? Number(v) : 0;
const text = (v: unknown) => String(v ?? "").toLowerCase();
const expectedCtr = (position: number) => position <= 3 ? 0.12 : position <= 10 ? 0.04 : position <= 20 ? 0.015 : 0.008;
type MetricRow = { id?: string; page_url?: string; query?: string; clicks?: number; impressions?: number; ctr?: number; position?: number; matched_catalog_item_id?: string | null; matched_proposal_id?: string | null; match_confidence?: number | null; optimization_proposals?: unknown; catalog_items?: unknown; proposal?: unknown };
type ProposalRow = { id: string; current_snapshot?: Record<string, unknown>; active_scores?: Record<string, number>; score_delta?: Record<string, number>; approved_version_id?: string | null; exported_at?: string | null };
function make(row: MetricRow, type: GscOpportunityType, score: number, title: string, description: string, action: string): Opportunity { return { id: `${type}:${row.id ?? row.page_url}:${row.query ?? "page"}`, source: "gsc", type, label: labelForGsc(type), priority: priorityFromScore(score), score: clampOpportunityScore(score), title, description, recommendedAction: action, href: row.matched_proposal_id ? `/app/proposals/${row.matched_proposal_id}` : row.matched_catalog_item_id ? `/app/catalog/${row.matched_catalog_item_id}` : "/app/search-console", pageUrl: row.page_url ?? null, query: row.query ?? null, catalogItemId: row.matched_catalog_item_id ?? null, proposalId: row.matched_proposal_id ?? null, clicks: n(row.clicks), impressions: n(row.impressions), ctr: n(row.ctr), position: n(row.position), matchConfidence: row.match_confidence ?? null, metrics: { clicks: n(row.clicks), impressions: n(row.impressions), ctr: n(row.ctr), position: n(row.position) } }; }
export function labelForGsc(type: GscOpportunityType) { return ({ gsc_high_impressions_low_ctr: "CTR bajo con demanda", gsc_quick_win_position_4_15: "Quick win 4-15", gsc_position_16_30_content_gap: "Brecha de contenido", gsc_impressions_no_clicks: "Impresiones sin clics", gsc_query_not_in_meta: "Query ausente en meta", gsc_query_not_in_title: "Query ausente en título", gsc_page_with_low_quality_score: "Demanda + calidad baja", gsc_missing_alt_with_impressions: "ALT con demanda", gsc_schema_gap_with_impressions: "Schema con demanda", gsc_geo_aeo_gap_with_impressions: "GEO/AEO con demanda", gsc_approved_not_exported_with_gsc_demand: "Aprobada con demanda", gsc_product_priority: "Producto prioritario" } as const)[type]; }
export function buildGscOpportunities(input: { urlMetrics?: MetricRow[]; pageQueryMetrics?: MetricRow[]; proposals?: ProposalRow[]; minImpressions?: number }): Opportunity[] { const min = input.minImpressions ?? 50; const byProposal = new Map((input.proposals ?? []).map((p) => [p.id, p])); const ops: Opportunity[] = [];
  for (const row of input.urlMetrics ?? []) { const impressions = n(row.impressions), clicks = n(row.clicks), ctr = n(row.ctr), position = n(row.position); if (impressions < min) continue; const p = row.matched_proposal_id ? byProposal.get(row.matched_proposal_id) : undefined; const quality = n(p?.active_scores?.overall); const base = Math.min(25, Math.log10(impressions + 1) * 8) + Math.min(25, Math.max(0, 16 - position) * 2) + (row.match_confidence ? n(row.match_confidence) * 10 : 0);
    if (ctr < expectedCtr(position) * 0.55) ops.push(make(row, "gsc_high_impressions_low_ctr", base + 30, `CTR bajo con ${impressions.toLocaleString("es-ES")} impresiones`, `La página tiene posición media ${position.toFixed(1)} y CTR ${(ctr * 100).toFixed(2)}%, por debajo de una referencia estimada para esa posición.`, "Revisar snippet y propuesta"));
    if (position >= 4 && position <= 15) ops.push(make(row, "gsc_quick_win_position_4_15", base + 25, `Quick win: posición ${position.toFixed(1)}`, "Google ya muestra esta URL en primera/segunda página; prioriza título, meta description y contenido sin keyword stuffing.", "Revisar oportunidad"));
    if (position > 15 && position <= 30) ops.push(make(row, "gsc_position_16_30_content_gap", base + 15, "Brecha de contenido 16-30", "La URL recibe impresiones pero aún necesita más relevancia/contenido para competir mejor.", "Mejorar contenido"));
    if (clicks === 0) ops.push(make(row, "gsc_impressions_no_clicks", base + 25, "Impresiones sin clics", "Hay demanda real, pero ningún clic en el rango sincronizado.", "Revisar CTR"));
    if (quality && quality < 65) ops.push(make(row, "gsc_page_with_low_quality_score", base + (65 - quality), "Demanda real + calidad interna baja", "Search Console muestra demanda y Rankelia detecta margen de calidad en la propuesta/producto.", "Priorizar producto"));
    if (p?.approved_version_id && !p.exported_at) ops.push(make(row, "gsc_approved_not_exported_with_gsc_demand", base + 35, "Aprobada con demanda, pendiente de exportar", "La versión aprobada corresponde a una URL con impresiones reales.", "Exportar aprobadas"));
  }
  for (const row of input.pageQueryMetrics ?? []) { const impressions = n(row.impressions), position = n(row.position); if (impressions < min) continue; const p = row.matched_proposal_id ? byProposal.get(row.matched_proposal_id) : undefined; const snapshot = p?.current_snapshot ?? {}; const query = text(row.query); const title = text(snapshot.meta_title ?? snapshot.seo_product_name); const meta = text(snapshot.meta_description); const base = 60 + Math.min(20, Math.log10(impressions + 1) * 5);
    if (query && !meta.includes(query.slice(0, Math.min(query.length, 35)))) ops.push(make(row, "gsc_query_not_in_meta", base, `Query real no reflejada en meta`, `La query “${row.query}” genera impresiones, pero no aparece de forma natural en la meta description activa.`, "Regenerar meta description"));
    if (position >= 4 && position <= 15 && query && !title.includes(query.slice(0, Math.min(query.length, 35)))) ops.push(make(row, "gsc_query_not_in_title", base + 5, `Query real no reflejada en título`, `La query “${row.query}” ya posiciona, pero el título activo no cubre claramente esa intención.`, "Regenerar meta title"));
  }
  return ops.sort((a, b) => b.score - a.score).slice(0, 100);
}
